const mongoose = require('mongoose')
const validator = require('validator')
const MenuSchema = new mongoose.Schema(
    {
        mens:
        [
            {
                upperWear:
                [
                    {
                        type:String
                    }
                ],
                bottomWear:
                [
                    {
                        type:String
                    }
                ],
                innerWear:
                [
                    {
                        type:String
                    }
                ]
            }
        ],
        women:
        [
            {
                indianWear:
                [
                    {
                        type:String
                    }
                ],
                westernWear:
                [
                    {
                        type:String
                    }
                ],
                activeWear:
                [
                    {
                        type:String
                    }
                ]
            }
        ],
        kids:
        [
            {
                boys:
                [
                    {
                        type:String
                    }
                ],
                girls:
                [
                    {
                        type:String
                    }
                ]
            }
        ],
        profile:
        [
            {
                type:String
            }
        ]
    })
const Menu = mongoose.model('Menu',MenuSchema)
module.exports = Menu